//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBConnect
{
    using System;
    using System.Collections.Generic;
    
    public partial class ToDoListCategory
    {
        public int ToDoList_Id { get; set; }
        public int Category_Id { get; set; }
        public int ToDoListCategoryID { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual ToDoList ToDoList { get; set; }
    }
}
